#region AutoGenerated
using UnityEngine;

namespace Pancake.Debugging
{
	/// <summary>
	/// Defines a channel for a message logged to the Console.
	/// <para>
	/// The contents of this class are auto-generated based on the channels added in Project Settings > Console.
	/// </para>
	/// <seealso cref="Debug.Log(int, string, Object)"/>
	/// </summary>
	public static class Channel
	{
		public const int None = 0;
		public const int yenmoc = 1;
	}
}
#endregion